### ISSUE TITLE
Support for jasmine

### ISSUE THREAD

**Issue by arturojain** [feross/standard#363] opened 2015-12-16 05:27 UTC
Currently it does not support the `it` and `describe` tags.

**Comment by yoshuawuyts** [comment] 2015-12-16 05:29
Duplicate of https://github.com/feross/standard/issues/18

Resolution was:
> Closing this for now, as the consensus seems to be that it's simplest to have mocha users just define globals in a comment.

Defining missing keywords in a comment should resolve your issue. Cheers!

**Closed by yoshuawuyts** 2015-12-16 05:29 UTC

**Comment by feross** [comment] 2015-12-17 06:42
@arturojain For more information, see this part of the readme: https://github.com/feross/standard#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors
