### ISSUE TITLE
Working with Babel's experimental transformers?

### ISSUE THREAD

**Issue by gsklee** [feross/standard#133] opened 2015-05-11 07:20 UTC
Is this compatible, or able to work with Babel's [experimental transformers](http://babeljs.io/docs/usage/experimental/) like decorators, object spread, etc.?

**Comment by julien-f** [comment] 2015-05-12 13:57
AFAIU, no.

standard is based on EsLint which does not support some features (e.g. ES7).

Using the [babel-eslint](https://github.com/babel/babel-eslint) parser would probably help but it is not clear atm how to integrate it properly (#106).

**Comment by feross** [comment] 2015-05-13 01:53
Duplicate of https://github.com/feross/standard/issues/106

**Closed by feross** 2015-05-13 01:53 UTC
