### ISSUE TITLE
Missing space before keyword "function" when function is inside an array

### ISSUE THREAD

**Issue by capaj** [feross/standard#387] opened 2016-01-15 18:19 UTC
this fails with: `3:23: Missing space before keyword "function".`
```
module.exports = function (toExtend) {
  return Object.assign(toExtend, {
    queryMiddleware: [function (query, user) {
      if (user.privilege_level < 20) {
        query.where('owner').equals(user._id) // if not admin, the user can only query his documents
      }
    }]
  })
}

```
this has no errors:
```
module.exports = function (toExtend) {
  return Object.assign(toExtend, {
    queryMiddleware: [ function (query, user) {
      if (user.privilege_level < 20) {
        query.where('owner').equals(user._id) // if not admin, the user can only query his documents
      }
    }]
  })
}
```

So this essentially forces me to have one space at the beginning of an array. Is this a bug? I think so.

**Comment by dcousens** [comment] 2016-01-17 01:18
Looks like a bug.
Simplified test case:

``` javascript
var x = {
  y: [function () { // Missing space before keyword "function".


  }]
}

console.log(x)
```

Add the space before `function` and it works.  **Bug**.

**Comment by kaicataldo** [comment] 2016-01-28 05:43
This seems to be the intended behavior of ESLint's `space-before-keywords` rule: http://eslint.org/docs/rules/space-before-keywords.html

**Comment by feross** [comment] 2016-02-04 02:51
This issue is caused by the keyword spacing rules that we have enabled conflicting with other spacing rules that we have enabled.

Fortunately, the next version of eslint (which will ship in standard v6) has a new, better rule `keyword-spacing` which doesn't check conditions which are handled by other rules.

From [the docs](http://eslint.org/docs/2.0.0/rules/keyword-spacing):

> This rule is designed carefully to not conflict with other spacing rules. Basically this rule ignores usage of spacing at places that other rules are catching. So the following patterns are considered not problems.

This is fixed on the `v6` branch and will be released as standard v6 soon.

**Closed by feross** 2016-02-04 02:51 UTC
Labels: bug
