### ISSUE TITLE
Global return error

### ISSUE THREAD

**Issue by dcousens** [feross/standard#148] opened 2015-05-30 02:18 UTC
Despite `globalReturn` being `true`,  I still get `Illegal return statement` when I use `return` in a self-contained translation unit (file/module).

``` javascript
return
```

Isn't this behaviour is meant to be allowed?

**Comment by feross** [comment] 2015-05-30 03:31
Yes, this is meant to be allowed.

**Comment by feross** [comment] 2015-05-30 03:44
I found the issue with `git bisect`. Bug in eslint. Issue reported: https://github.com/eslint/eslint/issues/2636

I'm going to just remove support for ES6 modules until this is fixed, since it's marked "experimental" in eslint. If people really want ES6 modules, they can use a custom parser like babel-eslint (now supported).

**Comment by feross** [comment] 2015-05-30 03:47
This bug is fixed in 3.14.0. Will leave this issue open to track the eslint bug. We can re-enable ES6 modules when it's fixed.

**Comment by feross** [comment] 2015-05-30 03:52
Reverted in https://github.com/feross/eslint-config-standard/commit/537fbbe3e41ad1b4bd457bcb8e5b0fbb6f701cc4

**Comment by dcousens** [comment] 2015-05-30 04:35
I'm happy to wait for this to be fixed in `eslint`,  this is an edge case to begin with anyway.

**Comment by feross** [comment] 2015-05-30 04:39
@dcousens cool, sounds good

**Comment by feross** [comment] 2015-06-01 17:04
ESLint says this is working as intended:

> Modules can't be wrapped in function scope, so a global return isn't possible.

@dcousens Open to suggestions about how to proceed.

**Comment by dcousens** [comment] 2015-06-02 03:11
@feross well if it isn't possible, I say we stay entirely agnostic and set `globalReturn` to `false`?

At least then it will be consistent across development environments (node, browserify or otherwise).

IMHO anyway.

**Comment by Cuel** [comment] 2015-06-02 07:12
What if I in index.js wanted to do like this
```javascript
return console.error('missing parameter')
```
As in I'd like to exit without throwing an error. It woudn't be allowed in standard?

**Comment by dcousens** [comment] 2015-06-02 13:01
@Cuel more to the point, it isn't allowed in `eslint`,  due to a broad definition of `module` AFAIK.

**Comment by feross** [comment] 2015-06-06 20:33
@Cuel @dcousens I left a comment asking for more clever behavior from eslint here: https://github.com/eslint/eslint/issues/2636#issuecomment-109646506 Feel free to support / share your opinion.

**Comment by dcousens** [comment] 2015-06-06 23:24
@feross ES6 makes this difficult.

Perhaps we should just change `globalReturn: false`?  This is only going to become more annoying as time goes on.

**Comment by feross** [comment] 2015-06-07 06:00
Agreed.

**Closed** 2015-06-07 06:01 UTC
Labels: blocked-on-eslint

**Comment by watson** [comment] 2015-06-19 21:47
@feross this seems to be released on npm already, but I'm still getting the error though. Maybe it's just me who have misunderstood the issue here, but as far as I know shouldn't it fix this problem: https://gist.github.com/watson/a3b4a7a2babfe04cb499
