### ISSUE TITLE
Enforce capitalization of the first letter of a comment (capitalized-comments)

### ISSUE THREAD

**Issue by computersarecool** [feross/standard#682] opened 2016-11-10 19:38 UTC
I am wondering if this project favors sentence case or all lower case for comments?
i.e.
`// This is my comment`

or

`// this is my comment`

Or if it even matters.

**Comment by feross** [comment] 2016-11-23 18:37
I'm not entirely consistent in my own code, though I think proper capitalization is better. There's no rule for this in ESLint, but there's [a proposal](https://github.com/eslint/eslint/issues/6055) to add it. When that gets added, I'll post an issue to consider it.

**Comment by feross** [comment] 2017-01-07 02:46
ESLint now has a `capitalized-comments` rule.

I propose enable it, as follows:

```js
"capitalized-comments": [
        "error",
        "always",
        {
            "ignoreInlineComments": true,
            "ignoreConsecutiveComments": true
        }
    ]
```

**Comment by dcousens** [comment] 2017-01-07 06:03
Woo! 
I hate having to think about this :+1:

**Comment by timoxley** [comment] 2017-01-07 07:39
@feross not disagreeing but why `ignoreInlineComments`?

**Comment by feross** [comment] 2017-01-08 00:10
@timoxley Maybe you're right. I'll test the ecosystem impact of `ignoreInlineComments` enabled vs. disabled and report back here before merging this.

**Comment by dcousens** [comment] 2017-01-08 22:04
You typically see this for those who use the type systems analysis tools which pick up on inline comments for type declaration in standard JS code.  IIRC

**Comment by feross** [comment] 2017-01-11 10:31
@dcousens If we want to, we can explicitly allow certain uncapitalized words to start a comment without triggering this error. The rule supports exceptions. But a blanket exemption on inline comments is certainly simpler and won't need constant updating.

**Comment by Flet** [comment] 2017-01-11 16:55
The inline eslint pragmas need to all be lowercase:

```js
/* Eslint-env mocha */   // Does not work!
/* eslint-env mocha */   // Works!
```

I wonder how many other transpilers/helpers would break because of forced uppercase.
Flow? JSDoc?

I tending to thumbs down on this just because the value may not be worth the additional breakage (or the additional maintenance of a whitelist).

**Comment by yoshuawuyts** [comment] 2017-01-11 16:59
I don't think we should - I don't feel this particular rule would be
useful, and might, in fact, become frustrating. With stuff like code
comments, function names and what not there's simply too many edge cases

**Comment by feross** [comment] 2017-01-11 22:39
@Flet All eslint pragmas are special-cased by the rule already.

```
Note that the following words are always ignored by this rule: ["jscs", "jshint", "eslint", "istanbul", "global", "globals", "exported"]
```

JSDoc is not affected because those declarations all start with a symbol (`@`) and that's allowed.

@yoshuawuyts Personally, I think this is a pretty well-thought-out rule: http://eslint.org/docs/rules/capitalized-comments I'd like to try shipping it in the `standard` v9 beta if there isn't strong objection so we can see how it works in practice.

**Comment by timoxley** [comment] 2017-01-12 01:17
> Note that the following words are always ignored by this rule: ["jscs", "jshint", "eslint", "istanbul", "global", "globals", "exported"]

Yeah I'm a little concerned about accidentally breaking non-eslint/less popular/custom pragmas. Would be interested to see ecosystem impact.

**Comment by jprichardson** [comment] 2017-01-13 14:52
Wouldn't commented out code be affected as well? If so, this seems pretty overreaching.

**Comment by feross** [comment] 2017-01-13 21:07
@jprichardson That's a good point that I hadn't considered. This rule basically prevents commented code from being committed.

For example, this would error:

```js
function foo (x) {
  // if (x === 1) return 10
  return x
```

In one way, it would be nice to prevent commented code from ending up in a codebase. But sometimes this is not avoidable, so I think I agree with @jprichardson now: this is a bit overreaching.

**Comment by jprichardson** [comment] 2017-01-13 23:33
Yeah, I agree in most cases, leaving commented code in place is a bad idea, especially since tools like Git are so pervasive. However, there are legitimate reasons to have commented code, like config files. Here is a real example from my codebase:

```js
export const EXODUS_SERVER = EXODUS_PRODUCTION_SERVER
// export const EXODUS_SERVER = EXODUS_STAGING_SERVER
```

`EXODUS_PRODUCTION_SERVER` and `EXODUS_STAGING_SERVER` are defined near the beginning of the file.

So now if I just implemented a new feature on the server, I can quickly uncomment the aforementioned block to this:

```js
// export const EXODUS_SERVER = EXODUS_PRODUCTION_SERVER
export const EXODUS_SERVER = EXODUS_STAGING_SERVER
```

and then the whole app is using `EXODUS_SERVER` still, but its value is different. Then when I'm ready to go back to a production build, I can change. Now I realize that it may be better to configure the aforementioned based upon `NODE_ENV`, but that'd feel like unnecessary ceremony required by a linter. 

I'm sure there's other cases that are equally as valid where this rule my impede.

**Comment by dcousens** [comment] 2017-01-13 23:42
@jprichardson sounds like a better use-case of `process.env`

**Comment by jprichardson** [comment] 2017-01-13 23:44
> @jprichardson sounds like a better use-case of process.env

You just have missed this part 😛 

> Now I realize that it may be better to configure the aforementioned based upon NODE_ENV, but that'd feel like unnecessary ceremony required by a linter.

**Comment by dcousens** [comment] 2017-01-14 03:04
@jprichardson I did,  so I edited :laughing:

**Comment by feross** [comment] 2017-02-09 01:35
This rule has a big ecosystem impact:

```
1..422
# tests 422
# pass  259
# fail  163
```

To reduce the impact, I investigated allowing commented out code by using the `ignorePattern` option. We can ignore comments that start with a JS reserved word (`do`, `if`, `in`, `for`, `let`, etc.). Comments that start with non-ascii characters are automatically allowed (`[`, `(`, etc.)

So, if we only catch comments with real words that need to be capitalized, we get:

```
1..422
# tests 422
# pass  268
# fail  154
```

This is automatically fixable, so it's a quick fix. But jury's out on whether we actually want to do this.

**Comment by feross** [comment] 2017-02-09 01:36
For example, here are some diffs after running `standard --fix`:

![screen shot 2017-02-08 at 5 35 16 pm](https://cloud.githubusercontent.com/assets/121766/22765421/0ecc8e72-ee25-11e6-87d3-65b96fd1ab6d.png)
![screen shot 2017-02-08 at 5 35 28 pm](https://cloud.githubusercontent.com/assets/121766/22765422/0ecf4612-ee25-11e6-8100-de3b35a87740.png)

**Comment by yoshuawuyts** [comment] 2017-02-09 02:06
No please

**Comment by feross** [comment] 2017-02-09 02:13
Leaving open for more feedback, but yeah, I tend to agree with you @yoshuawuyts

**Comment by timoxley** [comment] 2017-02-09 02:13
This has good intentions but my feeling is that the benefits are minimal and likelihood of it being a nuisance is high. Also don't like the risk of hard-to-detect logic corruption caused by uppercasing commented out source which is later uncommented.

**Comment by feross** [comment] 2017-02-09 02:14
@dcousens thoughts?

**Comment by timoxley** [comment] 2017-02-09 02:21
Along similar lines, maybe one could consider enforcing a particular formatting for multi-line jsdoc `/**` styled comments i.e. ensure jsdoc style comments conform to the/a particular jsdoc spec.

**Comment by dcousens** [comment] 2017-02-09 03:08
Agreed with @timoxley,  its junk to think about,  but,  its harmless by definition and IMHO,  not worth the community impact at all.
I could not morally justify this refactor to someone paying the bills, haha.

**Comment by feross** [comment] 2017-02-09 03:10
Alright, it's decided. 💀

**Closed by feross** 2017-02-09 03:10 UTC
Labels: new rule request

**Comment by Flet** [comment] 2017-02-09 03:49
This has been a great thread :)
