### ISSUE TITLE
Why spaces instead of tabs?

### ISSUE THREAD

**Issue by ibc** [feross/standard#622] opened 2016-09-14 14:27 UTC
Sorry, I know this is not an "issue", but I wonder why the "standard" should force me to use spaces instead of tabs for indentation.

When using spaces, I'm forcing every one else to see my code as I like. In certain monitors/resolutions 2 spaces could be a bad choice.

By using tabs, anyone can configure his text editor to display tabs with the desired visual width (for example, 2 or 4 spaces), and we all are happy.

I've been **never** told about a **real** advantage of using spaces instead of tabs.

**Comment by LinusU** [comment] 2016-09-14 14:44
Duplicate of #58

**Comment by ibc** [comment] 2016-09-14 15:04
#58 is not just closed, but also locked (after just 6 comments). So no debate, right?

It is also so funny how #58 ends:

> If you care a lot about tabs vs spaces, standard isn't for you.

I should not care about tabs vs spaces because you authors already did for me, right?

IMHO you should have chosen any other name for this library. This is not the "standard" of anything but the way you authors code, nothing else.

**Comment by feross** [comment] 2016-09-14 16:12
I'll just leave this here: https://www.youtube.com/watch?v=SsoOG6ZeyUI

You're right that tabs have some benefits. Spaces have some benefits too. The main issue with this topic (and why the previous issue was locked) is that this is not something that the maintainers of `standard` have any interest in debating. There are plenty of blog posts about why spaces are better than tabs if you want to go hunting for reasons.

You have the whole rest of the internet to debate the merits of spaces vs. tabs. This is not the place, sorry.

**Closed by feross** 2016-09-14 16:12 UTC

**Comment by ibc** [comment] 2016-09-14 16:26
I already knew that video, so nice :)

OK, I just assume `standardjs` is not for me, and I respect your decision. Just:

> Spaces have some benefits too

That's the only rationale I've found regarding spaces benefits: none (or undefined).

**Comment by feross** [comment] 2016-09-14 17:14
The reason that `standard` prefers spaces is simple: The most popular way of indenting JavaScript is with spaces. There are people who have written about why spaces may be better, if you're interested: http://paul-m-jones.com/archives/2312

**Comment by ibc** [comment] 2016-09-14 18:28
The two arguments in favor of styles in that post are mainly wrong:

#### Inter-Line Alignment

Even when I use TAB for indentation, I do NOT use TAB for "inter-line alignment" but spaces. That's not "indentation" but "text decoration". 

#### Line Length Recognition

Well, a problem if (as the post states) someone sets a virtual **8-space!!** width for TAB...

**Comment by feross** [comment] 2016-09-14 19:03
As mentioned before, I'm not interested in debating spaces vs. tabs.
