### ISSUE TITLE
"standard --fix" alters indentation on comments

### ISSUE THREAD

**Issue by 11tracer** [feross/standard#649] opened 2016-10-06 18:33 UTC
I'm trying out standard and I've noticed a bit of an odd behavior. It seems to enforce that all comments have a space before they start:

`// like so`

However, when I run "standard --fix" on my code, it will indent some comments that it fixes one or two extra times, like this, causing them to become misaligned with the code below them:

Before fixing:

```
code here
  //comment here
  code here
```

After fixing:

```
code here
    // comment here
  code here
```

This doesn't look right to me. Is this the intended behavior?

**Comment by 11tracer** [comment] 2016-10-06 19:39
I just realized that my comments were not being indented, it's that they were not being un-indented along with the rest of my code. Is there a way to apply the 2-space indenting rule to comments as well?

**Comment by timoxley** [comment] 2016-10-06 20:41
can you give a concrete example?

**Comment by feross** [comment] 2016-10-07 06:52
Space after `//` is an intentional rule:

```js
// this is okay
//this is not okay
```

As for your other issue, you'll need to provide a code example where it happens before we can look into it.

**Comment by 11tracer** [comment] 2016-10-07 12:07
Of course, sorry about that. So, for example something like this (which uses 4 spaces for indentation):

```javascript
const testFun = () => {
    //comment
    const test = 'test'
    return test
}
```

will be corrected to use 2 spaces, except for the comment.

```javascript
const testFun = () => {
    // comment
  const test = 'test'
  return test
}
```

Just to clarify, I have no issue with the space after `//` rule, it's that the 2-spaces-for-indentation rule is causing some comments to become misaligned with code. I was just misunderstanding what was causing the misalignment at first.

**Comment by feross** [comment] 2016-10-07 23:19
@11tracer Thanks for the code example. You're right -- confirmed.

**Comment by feross** [comment] 2016-10-08 02:59
Turns out this is a longstanding issue in ESLint (https://github.com/eslint/eslint/issues/3845). There's a rewrite of the `indent` rule underway (90% done) that will resolve this: https://github.com/eslint/eslint/issues/7274

So going to close this issue as there's nothing for us to do. We'll get the fix for free in a future ESLint version.

**Closed by feross** 2016-10-08 02:59 UTC
Labels: bug
