### ISSUE TITLE
Enforce only 1 newline at end of file (currently 1-2 are allowed)

### ISSUE THREAD

**Issue by johannes-z** [feross/standard#733] opened 2017-01-05 16:25 UTC
If there are spaces on the last line, `standard --fix` will remove the spaces, but still add a newline. 

In the following example I added characters to visualize newlines and spaces. An empty line is marked with a `_` (underscore) and a space is marked with a `.` (dot).

## Correct:
```js
console.log('test');
```
becomes
```js
console.log('test')
_
```

## Wrong:
```js
console.log('test');\n
..
```
becomes
```js
console.log('test')
_
_
```

**Comment by feross** [comment] 2017-01-05 22:15
This looks like an ESLint bug, so I opened an issue there: https://github.com/eslint/eslint/issues/7866

**Comment by feross** [comment] 2017-01-11 09:27
Turns out the way ESLint counts lines at the end of the file is a bit wonky. They don't count the last `\n`, so we actually need to set `maxEOF: 0` on the `no-multiple-empty-lines` rule:

```
    "no-multiple-empty-lines": [2, { "max": 1, "maxEOF": 0 }],
```

That fixes this issue, and also another issue where `standard` allows either 1 or 2 newlines at the end of a file. 👍

**Comment by feross** [comment] 2017-02-09 01:05
This will be part of standard v9. There were 12 repos that failed, but this is trivial to fix, is also automatically fixable with `--fix`, and was an enforced rule in the past (this was a regression).

**Closed by feross** 2017-02-09 01:05 UTC
Labels: bug
