### ISSUE TITLE
Rename your project to avoid confusion with ECMA standard

### ISSUE THREAD

**Issue by gkatsanos** [feross/standard#784] opened 2017-02-11 17:46 UTC
As pointed out by @gaearon [there](https://github.com/feross/standard/issues/78#issuecomment-85660078), cleverly naming this (otherwise very interesting) project as "standard" confuses people, often even people who're not even beginners. 

Even though I applaud the marketing skills, I do think you should consider renaming your project or clearly stating in your Readme some of the risks of some of your rules as well as stating clearly it's not related to any official ECMA standards body or anything like that. 

cheers

**Comment by LinusU** [comment] 2017-02-11 18:16
Feels like a duplicate of the issue you linked (#83)?

Anyhow, I don't think that there is any need for a name change, and this is also addressed in the readme:

> ## But this isn't a real web standard!
>
> Of course it's not! The style laid out here is not affiliated with any official web
standards groups, which is why this repo is called `feross/standard` and not
`ECMA/standard`.
>
> The word "standard" has more meanings than just "web standard" :-) For example:
>
> - This module helps hold our code to a high *standard of quality*.
> - This module ensures that new contributors follow some basic *style standards*.

I also don't understand this part:

> clearly stating in your Readme some of the risks of some of your rules

I don't see any risks at all with using standard, can you provide an example?

**Closed** 2017-02-11 18:17 UTC

**Comment by gaearon** [comment] 2017-02-11 19:09
FWIW I've stopped caring a long time ago and I recommend everyone to do the same 😉
