### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by naknode** [feross/standard#36] opened 2015-02-19 04:08 UTC
I am on Windows 7 (64-bit) and did `npm install standard -g` and tried doing it.

 I get this error:
```
c:\wamp\www\qtsite\src\js (master)
λ standard
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by Flet** [comment] 2015-02-19 05:39
Hmm, could this be some regression since #4?

**Comment by feross** [comment] 2015-02-19 08:57
It's very possible.

**Comment by Flet** [comment] 2015-02-19 21:13
Running node v0.10.26 and npm@1.4.3 on Windows I get the same error above. 

Upgrading to the lastest version of node v0.12.0 seems to get around these errors, however a new error is revealed:
```
Unexpected Linter Output:
Could not find formatter 'C:\Users\flettrdc\AppData\Roaming\npm\node_modules\standard\lib\eslint-reporter-verbose.js'.
```

It looks like its this `eslint` bug which has been fixed but not released to npm:  eslint/eslint#1818

@naknode what version of node/npm do you have installed?
```
node -v
npm -v
```

**Comment by feross** [comment] 2015-02-19 21:33
We probably lost node 0.10.x support when we switched to the [`npm run` approach](https://github.com/feross/standard/blob/master/index.js#L140) of executing `eslint` and `jscs`. That change was necessary to ensure we always get the correct path to the binary, even when npm does deduping.

Looks like we'll be all good once eslint does a release.

**Comment by naknode** [comment] 2015-02-19 23:48
I updated my node to node v0.12.0 and it works :)

```
c:\wamp\www\qtsite\src\js (master)
λ standard
Error: Use JavaScript Standard Style (https://github.com/feross/standard)
  demo-page.js:2:2: Expected indentation of 2 characters
  main.js:2:4: Expected indentation of 4 characters
  main.js:28:34: Expected no padding newline after opening curly brace
  main.js:43:0: Expected no padding newline before closing curly brace
  main.js:52:2: Expected indentation of 2 characters

Unexpected Linter Output:
Could not find formatter 'C:\Users\Dan\AppData\Roaming\npm\node_modules\standard\lib\eslint-reporter.js'.
```

**Comment by Flet** [comment] 2015-02-19 23:52
Excellent, looks like its just waiting for `eslint` now to get the other half working~

**Comment by feross** [comment] 2015-02-21 22:37
Going to close this now, as the `spawn ENOENT` error can be fixed by updating to node 0.12.

**Closed by feross** 2015-02-21 22:37 UTC

**Comment by feross** [comment] 2015-02-26 12:32
`eslint` published 0.15 with the necessary windows fix, and we're pulling that in in `standard` 2.8.0 now.

@naknode Please update to the latest `standard` and confirm that that eslint error is gone :)

**Comment by naknode** [comment] 2015-02-26 18:39
Can confirm it works with no errors. Thanks! Time to use it woo.

**Comment by naknode** [comment] 2015-02-26 18:39
@feross  Can confirm it works with no errors. Thanks! Time to use it woo.

**Comment by riophae** [comment] 2015-03-06 02:54
I'm running iojs v1.4.3 and standard 2.10.0. Got the same error.
```
D:\Node.js Projects\fanfou-wap-style-enhancer
λ standard
Error: spawn Active code page: 65001
Active code page: 65001
C:\Users\Riophae Lee\AppData\Roaming\NPM\node_modules\standard\node_modules\.bin\jscs.CMD ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1022:32)
    at child_process.js:1114:20
    at process._tickCallback (node.js:350:11)
```

**Comment by feross** [comment] 2015-03-06 21:38
I don't have a windows machine to debug this. If a windows user figures this out, please send a PR and we'll merge it.
