### ISSUE TITLE
Disallow padded blocks (blank lines at start/end of block statements)

### ISSUE THREAD

**Issue by LinusU** [feross/standard#170] opened 2015-06-24 08:49 UTC
*I apologize if there has been an issue on this but I couldn't find it when searching.*

I'm very sure that this wasn't allowed earlier, was the change to allow this intentional?

```javascript
function test () {

  return 12
}
```

I think it's very good to enforce something here, either always empty line at start of function, or never. Or is there a good reason to sometimes allow it?

I like to think that standard is so good that there will be just one correct output from any AST. Obviously we'll never get quite there, but I believe that being more strict is better.

-----

Bug progress:

- [x] ahmadnassri/echint
- [x] ahmadnassri/forwarded-http
- [x] ahmadnassri/har-validator
- [x] ahmadnassri/har-expander
- [x] feross/buffer
- [x] feross/bittorrent-tracker
- [x] feross/typedarray-to-buffer
- [x] feross/StudyNotes
- [x] feross/webtorrent-www
- [x] feross/whiteboard
- [x] feross/webtorrent
- [x] Flet/standard-engine
- [x] maxogden/dat-core
- [x] maxogden/requirebin
- [x] maxogden/dat
- [x] maxogden/torrent
- [x] mcollina/fastfall
- [x] mcollina/fastq
- [x] mcollina/hyperemitter
- [x] moose-team/friends
- [x] motdotla/dotenv
- [ ] npm/docs

**Comment by feross** [comment] 2015-06-24 08:54
You shouldn't pad blocks -- you're correct. The eslint rule that enforces this is [`padded-blocks`](http://eslint.org/docs/rules/padded-blocks).

Unfortunately, we had to disable it in https://github.com/feross/standard/commit/6f75ec3c5ae1502b924f37ebb078d8c2b3a1dc40 because eslint 0.19 started incorrectly reporting errors in code that uses ASI. We can re-enable the rule once this issue (eslint/eslint#2336) is fixed.

**Comment by feross** [comment] 2015-06-24 08:57
I just put $10 on the issue. If you're willing, please chip in and they'll fix it faster.

**Comment by feross** [comment] 2015-07-13 21:25
This is fixed in eslint `master`, but we need to wait for an npm release.

**Comment by feross** [comment] 2015-07-17 06:33
This will be fixed in eslint 1.0.0 and standard 5.0.0. https://github.com/feross/standard/issues/192

**Comment by LinusU** [comment] 2015-08-13 06:38
@feross this is still broken in 5.0.2 :sob: 

```text
➜  /tmp  cat test.js     
function test () {

  return 1

}

test()
➜  /tmp  standard --version
5.0.2
➜  /tmp  standard test.js
➜  /tmp  
```

**Comment by dcousens** [comment] 2015-08-13 06:39
Confirmed still in `5.0.2`.

``` javascript
function test () {

  return 1

}

test()
```

**Comment by feross** [comment] 2015-08-14 01:43
This is actually a huge breaking change at this point. 22 out of 138 sample repos fail if we enable this rule.

Since this isn't a very important rule -- it doesn't affect code correctness -- I'm inclined to not add this rule back. Or, if we do, it'll have to be in v6.0.0 when/if there are other breaking rules.

But I really want `standard` to be "done" at some point, so we can stop futzing with the rules and just be productive (which was kinda the whole point of this module ;) Ideally, there won't be a v6.0.0 for a long time.

**Comment by dcousens** [comment] 2015-08-14 01:46
@feross it was my understanding that this rule was meant to be in place a while ago.  I see no reason why we can't just fix up those 22 repositories,  the rule has been around long enough that it seems like most users should have been aware of it?

It would seem very odd for us to enforce consistent spacing in objects,  but not in functions.

**Comment by LinusU** [comment] 2015-08-14 07:59
I would really like to see that rule added back. I can volunteer to submit 22 pull requests to get this moving.

![200](https://cloud.githubusercontent.com/assets/189580/9269522/d957beae-426a-11e5-812d-0faa4d3210e9.gif)

As said this rule have been in place for a long time and I think that many people are aware of it, it's easy to miss in one or two places though. Just noticed it in one of my own project, which is what led me to open this issue.

Hopefully I can compile a list of the repos and start working on it during this weekend.

**Comment by feross** [comment] 2015-08-14 12:23
@LinusU Okay, if you get the tests passing, I'm okay with merging this and releasing it in a minor release.

**Comment by LinusU** [comment] 2015-08-14 20:54
Okay, 22 pull requests sent! Took me just half an hour, nice :sunglasses:

**Comment by LinusU** [comment] 2015-08-14 20:56
First merged! Only 21 to go, I'll edit the first post so that it shows the progress on the issue

**Comment by mcdonnelldean** [comment] 2015-08-14 21:08
@LinusU Second one has just come in :dancer: Hyperemitter has updated too.

**Comment by LinusU** [comment] 2015-08-14 21:09
Super! :fireworks:

I've updated the list :clap:

**Comment by mcdonnelldean** [comment] 2015-08-14 21:12
In terms of @mcollina 's other ones, I'll ping him for access when he gets back.

**Comment by dcousens** [comment] 2015-08-15 11:22
@LinusU,  awesome work.

**Comment by mcollina** [comment] 2015-08-19 07:54
I'm back ;). On this.

**Comment by LinusU** [comment] 2015-08-19 09:07
Only two repos to go now :+1:

**Comment by LinusU** [comment] 2015-08-31 07:34
@feross There are two holdouts, can we go ahead anyway?

**Comment by dcousens** [comment] 2015-08-31 12:17
LGTM

**Comment by LinusU** [comment] 2015-08-31 20:20
It's only npm/docs that's holding out now

**Comment by feross** [comment] 2015-09-03 13:55
Sure, let's go ahead.

Released as 5.2.0.

**Closed by feross** 2015-09-03 13:55 UTC
Labels: blocked on eslint, bug

**Comment by LinusU** [comment] 2015-09-03 14:04
Cool :+1:

**Comment by franciscop** [comment] 2016-05-16 15:36
Could this be reopened until it's documented somewhere (and fixed)? Having to hunt down closed issues to see why the error is there since nothing like this is document is a bit weird...

**Comment by feross** [comment] 2016-05-16 17:16
@franciscop Padded blocks are disallowed in `standard`. Not sure what your issue is. If you have a new bug to report, please open a new issue.
