### ISSUE TITLE
Global variables options in command line.

### ISSUE THREAD

**Issue by LeiZeng** [feross/standard#200] opened 2015-07-21 12:32 UTC
Hi, @feross ,

I know we can set options in package.json or put some comments in the head of the files.
But we still met some troubles when use some plugins in our Editors(like Atom), the cwd is no longer the root path of our project, so if we could have some options to config the global variables in the command line like the ignores, it will be perfect!!

**Comment by dcousens** [comment] 2015-07-21 13:12
![](http://i.imgur.com/qtu4jkX.png)

**Comment by ricardofbarros** [comment] 2015-07-22 12:08
+1, 

Was looking to add this feature on `linter-js-standard` but it seems like this isn't supported on standard CLI.

@dcousens Yeah it could be very slippery since we need to pass a serialised array on CLI args
@feross What are your thoughts on this?

**Comment by feross** [comment] 2015-07-22 14:57
@ricardofbarros 
The simple argument parser we use (`minimist`) returns an array when a command line flag is used twice:

```
standard --global React --global OtherGlobal
````

So no worries there.

**Comment by feross** [comment] 2015-07-22 14:59
@dcousens 

I'm fine adding a command line flag for anything that's configurable in `package.json`. You can already set the parser in `package.json` and on the command line. But, more generally, your point is taken :)

**Comment by ricardofbarros** [comment] 2015-07-22 15:03
Cool :smile:

**Comment by feross** [comment] 2015-07-22 16:21
Released as 5.0.0-3. This is a prerelease version, so beware that breaking changes may be added before 5.0.0 is released.

**Closed by feross** 2015-07-22 16:21 UTC
Labels: question

**Comment by ricardofbarros** [comment] 2015-07-22 17:31
I couldn't make the CLI to accept `--global` arg, can anyone test to see if it's working?

**Comment by feross** [comment] 2015-07-22 23:43
Published 5.0.0-4 and confirmed that it works.

**Comment by dcousens** [comment] 2015-07-23 03:09
@feross :+1: happy with that.
