### ISSUE TITLE
Expected "[" and "]" to be on the same line (standard/computed-property-even-spacing)

### ISSUE THREAD

**Issue by jprichardson** [feross/standard#226] opened 2015-08-08 19:51 UTC
Using `standard@4.5.4` in conjunction with `babel-eslint@4.0.5` there is no error in the following code:

```js
import fn from 'fn'

export default function something (args) {
  return fn({
    field: 'blah',
    ...args
  })
}
```

However, upgrading to `standard@5.0.2` an error is thrown:

    app.js:6:5: Expected "[" and "]" to be on the same line (standard/computed-property-even-spacing)

Potentially a bug in https://github.com/xjamundx/eslint-plugin-standard/tree/master or is this expected behavior?

**Comment by jprichardson** [comment] 2015-08-08 19:53
Sorry, I should have dug around in the proper repo! https://github.com/xjamundx/eslint-plugin-standard/issues/3

**Comment by albertorestifo** [comment] 2015-08-13 16:53
:+1: 

![image](https://cloud.githubusercontent.com/assets/1037048/9255906/95c50724-41ec-11e5-80f5-05a416df6e74.png)

![image](https://cloud.githubusercontent.com/assets/1037048/9255901/9099a6e2-41ec-11e5-840d-23920827100a.png)

**Comment by dcousens** [comment] 2015-08-13 21:20
Close?
As https://github.com/xjamundx/eslint-plugin-standard/issues/3 is where this is tracking.
@feross or do we have a `blocked-on-eslint-standard-plugin`?

**Comment by feross** [comment] 2015-08-14 12:15
This is fixed in standard 5.1.0.

**Closed by feross** 2015-08-14 12:15 UTC
Labels: bug

**Comment by davidmarkclements** [comment] 2016-01-04 20:20
seems to have returned in 5.4.1: 


```sh
MacBook-Pro:src davidclements$ standard --version
5.4.1
MacBook-Pro:src davidclements$ standard components/Settings/index.js
standard: Use JavaScript Standard Style (https://github.com/feross/standard)
  /Users/davidclements/z/nearForm/terminal-devtools/src/components/Settings/index.js:17:3: Expected "[" and "]" to be on the same line
```


```js
14 const settings = {
15  border: null,
16  padding: {left: 1, right: 1},
17  ...bg
18 }
```

**Comment by feross** [comment] 2016-02-08 00:59
@davidmarkclements Sorry, I can't reproduce your issue with `standard` v6. Perhaps you can try upgrading?
