### ISSUE TITLE
Weird behavior with await

### ISSUE THREAD

**Issue by julien-f** [feross/standard#268] opened 2015-09-21 15:16 UTC
```js
(async function () {
  // Missing space before keyword "await".
  !await true

  // Unexpected space after unary operator "!".
  ! await true

  // Works.
  !(await true)
})()
```

**Comment by feross** [comment] 2015-09-21 16:54
This is caused by two rules that make sense alone but conflict in this situation, and other like it. I opened as an issue on eslint to get their feedback: https://github.com/eslint/eslint/issues/3878

**Comment by julien-f** [comment] 2015-09-23 13:10
It does not work either with string interpolation:

```
(async function () {
  console.log(`${await 'foo'}`)
})
```

So your proposal to disable this rule for unary operators does not really make sense.

`await` is very different from other keywords (`if`, `return`, etc.) as it is part of an expression and IMHO it should be treated differently, and the same goes for `yield`.

**Comment by LinusU** [comment] 2015-10-26 14:24
I found another strange behaviour which I think is the same as this:

```javscript
const [bread, butter] = [await breadPromise, await butterPromise]
```

> Missing space before keyword "await".

As you can see I don't use initial spaces in arrays (`[a, b]` vs. `[ a, b ]`) which standard is totally fine with, so it seems weird that I need to do it when using await.

**Comment by matjaz** [comment] 2016-01-26 19:52
any updates on this?

**Comment by feross** [comment] 2016-02-04 10:38
This issue is similar to #387. I'll repeat what I posted there earlier:

This issue is caused by the keyword spacing rules that we have enabled conflicting with other spacing rules that we have enabled.

Fortunately, the next version of eslint (v2) (which will ship in standard v6) has a new, better rule `keyword-spacing` which doesn't check conditions which are handled by other rules.

From [the docs](http://eslint.org/docs/2.0.0/rules/keyword-spacing) for `keyword-spacing`:

> This rule is designed carefully to not conflict with other spacing rules. Basically this rule ignores usage of spacing at places that other rules are catching. So the following patterns are considered not problems.

This is fixed on the `v6` branch and will be released as standard v6 soon.

**Closed by feross** 2016-02-04 10:38 UTC
Labels: blocked, question
